# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to learn and practice NumPy and Pandas

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [2]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [5]:
array1 = np.ones(10)
array2 = np.ones((25), dtype="int8")
array3 = array2.reshape(5,5)

print(array1)
print(array3)
print (array2.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
int8


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [11]:
arr1=np.random.randn(1,3,3,3)
arr2=arr1.reshape(27)
print(arr1)
print(arr2)

[[[[-1.76116722  0.54435694  1.8983032 ]
   [ 0.70296041  0.99596353 -0.04636536]
   [ 0.00665331  1.20910088 -0.10122989]]

  [[ 0.48514339 -0.12723327  0.70328544]
   [ 0.07889695  1.28546013  1.41361044]
   [ 1.47507154  1.40770013  0.9861629 ]]

  [[ 0.15714658  0.8713984  -0.21347372]
   [-0.90995681  0.39418482  0.17163791]
   [ 2.26272171  0.46295798 -0.10533171]]]]
[-1.76116722  0.54435694  1.8983032   0.70296041  0.99596353 -0.04636536
  0.00665331  1.20910088 -0.10122989  0.48514339 -0.12723327  0.70328544
  0.07889695  1.28546013  1.41361044  1.47507154  1.40770013  0.9861629
  0.15714658  0.8713984  -0.21347372 -0.90995681  0.39418482  0.17163791
  2.26272171  0.46295798 -0.10533171]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [18]:
arr3 = np.linspace(1, 10, num=20)
print(arr3)
# 1 and 10 represent start and stop
# num = 20 represents the number of numbers to include


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [20]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
# why minus 1?
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [4]:
20

20

In [22]:
print

IndexError: index 19 is out of bounds for axis 0 with size 5

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [7]:
# Code come here


```python
array([ 6,  7,  8,  9, 10])
```

In [8]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [9]:
# Code comes here

## 2.6 

Calculate the sum of each row in `a`.

In [10]:
# Code comes here

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [12]:
# Code comes here

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [23]:
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [30]:
df = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')
for column in df:
    print(column)

country
food_category
consumption
co2_emmission
country
food_category
consumption
co2_emmission


## 2.10 

How many rows and columns are there in the dataframe?

there are 4 columns, 1430 rows
starts on 0 so add 1 to final value

In [40]:
df.head(10)
df.tail(10)

country             food_category  consumption  co2_emmission
1420  Bangladesh                   Poultry         1.40           1.50
1421  Bangladesh                      Beef         1.28          39.50
1422  Bangladesh               Lamb & Goat         1.33          46.58
1423  Bangladesh                      Fish        18.07          28.85
1424  Bangladesh                      Eggs         2.08           1.91
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh                      Rice       171.73         219.76
1428  Bangladesh                  Soybeans         0.61           0.27
1429  Bangladesh   Nuts inc. Peanut Butter         0.72           1.27

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [36]:
print (df.describe())
df.mean
# the mean is 74.383

       consumption  co2_emmission
count  1430.000000    1430.000000
mean     28.110406      74.383993
std      49.818044     152.098566
min       0.000000       0.000000
25%       2.365000       5.210000
50%       8.890000      16.530000
75%      28.132500      62.597500
max     430.760000    1712.000000


<bound method NDFrame._add_numeric_operations.<locals>.mean of          country             food_category  consumption  co2_emmission
0      Argentina                      Pork        10.51          37.20
1      Argentina                   Poultry        38.66          41.53
2      Argentina                      Beef        55.48        1712.00
3      Argentina               Lamb & Goat         1.56          54.63
4      Argentina                      Fish         4.36           6.96
...          ...                       ...          ...            ...
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh                      Rice       171.73         219.76
1428  Bangladesh                  Soybeans         0.61           0.27
1429  Bangladesh   Nuts inc. Peanut Butter         0.72           1.27

[1430 rows x 4 columns]>

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [54]:
# max is 1712
df_max_co2 = df['co2_emmission'].max()
print (df_max_co2)

1712.0


## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [64]:
morethan1000 = df['co2_emmission']>1000
print(morethan1000)
morethan1000.head(35)
morethan = df.query('co2_emmission > 1000')[["country", "food_category", "consumption"]]
print(morethan)

# the answer is 5 countries,all are for beef

0       False
1       False
2        True
3       False
4       False
        ...  
1425    False
1426    False
1427    False
1428    False
1429    False
Name: co2_emmission, Length: 1430, dtype: bool
       country food_category  consumption
2    Argentina          Beef        55.48
13   Australia          Beef        33.86
57         USA          Beef        36.24
90      Brazil          Beef        39.25
123    Bermuda          Beef        33.15


## 2.14

Which country consumes the least amount of beef per person per year?


In [69]:
bermudafood = df[df["country"]=="Bermuda"]
# above is the correct formating for creating subsets of a df
print(bermudafood)

     country             food_category  consumption  co2_emmission
121  Bermuda                      Pork        28.24          99.96
122  Bermuda                   Poultry        32.62          35.04
123  Bermuda                      Beef        33.15        1022.94
124  Bermuda               Lamb & Goat         2.71          94.90
125  Bermuda                      Fish        33.22          53.04
126  Bermuda                      Eggs        14.92          13.71
127  Bermuda        Milk - inc. cheese        95.56         136.12
128  Bermuda  Wheat and Wheat Products        54.88          10.47
129  Bermuda                      Rice         5.38           6.88
130  Bermuda                  Soybeans         0.22           0.10
131  Bermuda   Nuts inc. Peanut Butter         5.72          10.12


In [61]:
just_beef = df[df["food_category"]=="Beef"]
# this creates just a subset including the data for all beef consumption
# you can then use .functions to figure out highest, lowest etc
print(just_beef.min())
# the value for least is 0.78
# this is for Albania
# not sure how to figure out which row this comes from

country          Albania
food_category       Beef
consumption         0.78
co2_emmission      24.07
dtype: object


## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [20]:
# need to create a new df that only includes these products

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [21]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assitance.